title:  Booj
tagline:  thoughts on security

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'booj-1'

google-ID: 'UA-111876212-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Series', path: 'menu', url: 'series.html'}
- {name: 'Wiki', path: 'menu', url: 'https://reboare.gitbooks.io/booj-security/content/'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/reboare'}
- {icon: 'twitter', link: 'https://twitter.com/reboare'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/josiah-beverton-1b1b22b1/'}
- {icon: 'envelope', link: 'mailto:josiah.beverton@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
